version: '3.9'

services:
  node:
    build: .
    ports:
        - '3000:3000'
    volumes:
      - './usr/src/app'

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres